# ----------------------------
# Makefile Options
# ----------------------------

NAME = SUDOKU
ICON = icon.png
DESCRIPTION = "Sudoku for TI-84 Plus CE"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
