# ----------------------------
# Chess Engine CE Benchmark
# ----------------------------

NAME = CHBENCH
ICON = icon.png
DESCRIPTION = "Chess engine benchmark"
COMPRESSED = NO
HAS_PRINTF = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
